---
language: node_js
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - .jest
jobs:
  include:
    - stage: 'Pipeline'
      script:
        - yarn test --ci
        - yarn semantic-release
        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - expo publish --non-interactive
