---
language: node_js
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - .jest
jobs:
  include:
    - stage: 'Pipeline'
      script:
        - yarn test --ci
        - expo publish
        - yarn semantic-release
