---
language: node_js
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - .jest
jobs:
  include:
    - stage: test
      script:
        - yarn test --ci
    - stage: deploy
      script:
        - yarn semantic-release
        - yarn publish
