---
language: node_js
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - .jest
jobs:
  include:
    - stage: 'Pipeline'
      script:
        - yarn test --ci
        - expo login -u <EXPO USERNAME> -p <EXO PASSWORD>
        - expo publish --non-interactive
        - yarn semantic-release
