---
language: node_js
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g yarn
jobs:
  include:
    - stage: deploy
      script:
        - yarn test --ci
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
